### ISSUE TITLE
Delay UI

### ISSUE THREAD

**Issue by AlbertSmit** [OTTO-project/OTTO#71]
There needs to be a UI for the Delay DSP that Jonatan has done.

There is 4 parameters for the Delay:
* Delay time
* feedback
* filter frequency
* stereo spread+flanger

Any suggestion/idea/concept is welcome; please see the UI guidelines.

**Comment by danielku** [comment]
draft for the recorder / tape mode, because many ppl were with the idea of a facility.

![scarf](https://user-images.githubusercontent.com/4124730/43806647-1a9153a4-9aa5-11e8-893d-3cded74cbef9.png)

**Comment by zacYP2** [comment]
possible inspiration:

![delay](https://user-images.githubusercontent.com/28604041/43951436-2562d2ea-9c61-11e8-8bf1-ec9b83254b1a.png)

**Comment by zacYP2** [comment]
should we merge with this old thread? is it still relevant?

https://github.com/topisani/OTTO/issues/33

**Comment by zacYP2** [comment]
Maybe we drop the top line that is the smallest, and just start from the biggest one? That we with no effect we see one big arc, then with one feedback we see a smaller one under, etc. util the smallest one that we seee now is max feedback.

As mmuch as the small line we see adds to the roundness feeling, I think it hinders comprehension.

**Comment by topisani** [comment]
Where did we end up on this?
